/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'totalFee' : IDL.Nat,
  'emiOptions' : IDL.Vec(IDL.Nat),
});
export const Result_7 = IDL.Variant({ 'ok' : Course, 'err' : IDL.Text });
export const UserId = IDL.Principal;
export const CourseCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : UserId,
  'description' : IDL.Text,
});
export const Result_6 = IDL.Variant({
  'ok' : CourseCategory,
  'err' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const FollowUp = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'reminderDate' : IDL.Opt(Timestamp),
  'leadId' : IDL.Nat,
  'notes' : IDL.Text,
  'nextFollowUpDate' : Timestamp,
});
export const Result_5 = IDL.Variant({ 'ok' : FollowUp, 'err' : IDL.Text });
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'dropped' : IDL.Null,
  'followUp' : IDL.Null,
  'converted' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'assignedTo' : IDL.Opt(UserId),
  'source' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
  'courseId' : IDL.Nat,
});
export const Result_4 = IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text });
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'online' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'studentId' : IDL.Nat,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'confirmedAt' : IDL.Opt(Timestamp),
  'confirmedBy' : IDL.Opt(UserId),
  'paymentLink' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const Result_11 = IDL.Variant({ 'ok' : Payment, 'err' : IDL.Text });
export const ReminderTargetType = IDL.Variant({
  'emi' : IDL.Null,
  'followUp' : IDL.Null,
  'payment' : IDL.Null,
});
export const ReminderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'sent' : IDL.Null,
  'failed' : IDL.Null,
});
export const ReminderRecipientType = IDL.Variant({
  'all' : IDL.Null,
  'teamHead' : IDL.Null,
  'admin' : IDL.Null,
  'student' : IDL.Null,
  'counselor' : IDL.Null,
});
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReminderStatus,
  'sentAt' : IDL.Opt(Timestamp),
  'message' : IDL.Text,
  'targetType' : ReminderTargetType,
  'targetId' : IDL.Nat,
  'recipientType' : ReminderRecipientType,
  'scheduledAt' : Timestamp,
});
export const Result_12 = IDL.Variant({ 'ok' : Reminder, 'err' : IDL.Text });
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'headId' : IDL.Opt(UserId),
});
export const Result_1 = IDL.Variant({ 'ok' : Team, 'err' : IDL.Text });
export const StudentStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'inactive' : IDL.Null,
});
export const PaymentType = IDL.Variant({ 'emi' : IDL.Null, 'full' : IDL.Null });
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'status' : StudentStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'totalFee' : IDL.Nat,
  'leadId' : IDL.Opt(IDL.Nat),
  'assignedCounselor' : IDL.Opt(UserId),
  'enrolledAt' : Timestamp,
  'paymentType' : PaymentType,
  'phone' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
  'paidAmount' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const Result_2 = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
export const Result_8 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const Result_10 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const ActivityLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'userId' : UserId,
  'entityId' : IDL.Opt(IDL.Nat),
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const Role = IDL.Variant({
  'accountant' : IDL.Null,
  'teamHead' : IDL.Null,
  'admin' : IDL.Null,
  'counselor' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'teamId' : IDL.Opt(IDL.Nat),
});
export const EmiStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'overdue' : IDL.Null,
});
export const EmiInstallment = IDL.Record({
  'id' : IDL.Nat,
  'status' : EmiStatus,
  'studentId' : IDL.Nat,
  'installmentNumber' : IDL.Nat,
  'dueDate' : Timestamp,
  'paidDate' : IDL.Opt(Timestamp),
  'paymentId' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'convertedStudents' : IDL.Nat,
  'recentActivities' : IDL.Vec(ActivityLog),
  'totalLeads' : IDL.Nat,
  'overduePayments' : IDL.Nat,
  'upcomingEmi' : IDL.Vec(EmiInstallment),
  'pendingEmi' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'upcomingFollowUps' : IDL.Vec(FollowUp),
});
export const EmiReport = IDL.Record({
  'overdueAmount' : IDL.Nat,
  'pending' : IDL.Nat,
  'paid' : IDL.Nat,
  'overdue' : IDL.Nat,
  'totalInstallments' : IDL.Nat,
});
export const LeadReport = IDL.Record({
  'dropped' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'byStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'converted' : IDL.Nat,
});
export const Receipt = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'generatedAt' : Timestamp,
  'generatedBy' : UserId,
  'paymentId' : IDL.Nat,
  'amount' : IDL.Nat,
  'receiptNumber' : IDL.Text,
});
export const RevenueReport = IDL.Record({
  'emiRevenue' : IDL.Nat,
  'fullPayRevenue' : IDL.Nat,
  'confirmedPayments' : IDL.Vec(Payment),
  'totalRevenue' : IDL.Nat,
});
export const AppSettings = IDL.Record({
  'companyEmail' : IDL.Text,
  'whatsappApiKey' : IDL.Text,
  'smtpHost' : IDL.Text,
  'smtpPort' : IDL.Nat,
  'smtpUser' : IDL.Text,
  'logoUrl' : IDL.Text,
  'smsApiKey' : IDL.Text,
  'companyName' : IDL.Text,
  'companyPhone' : IDL.Text,
  'paymentBaseUrl' : IDL.Text,
});
export const Result_9 = IDL.Variant({
  'ok' : EmiInstallment,
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : AppSettings, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addCourse' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
      [Result_7],
      [],
    ),
  'addCourseCategory' : IDL.Func([IDL.Text, IDL.Text], [Result_6], []),
  'addFollowUp' : IDL.Func(
      [IDL.Nat, IDL.Text, Timestamp, IDL.Opt(Timestamp)],
      [Result_5],
      [],
    ),
  'addLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Result_4],
      [],
    ),
  'addPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, PaymentMethod, IDL.Opt(IDL.Text)],
      [Result_11],
      [],
    ),
  'addReminder' : IDL.Func(
      [ReminderTargetType, IDL.Nat, IDL.Text, Timestamp],
      [Result_12],
      [],
    ),
  'addTeam' : IDL.Func([IDL.Text, IDL.Opt(IDL.Nat), IDL.Text], [Result_1], []),
  'assignCourse' : IDL.Func([IDL.Nat, IDL.Nat], [Result_2], []),
  'assignLead' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Principal], [Result_4], []),
  'assignTeamHead' : IDL.Func([IDL.Nat, IDL.Principal], [Result_1], []),
  'confirmPayment' : IDL.Func([IDL.Nat], [Result_11], []),
  'convertLeadToStudent' : IDL.Func(
      [IDL.Nat, PaymentType, IDL.Opt(IDL.Nat)],
      [Result_2],
      [],
    ),
  'deleteCourse' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteCourseCategory' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteFollowUp' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteLead' : IDL.Func([IDL.Nat], [Result_8], []),
  'deletePayment' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteTeam' : IDL.Func([IDL.Nat], [Result_8], []),
  'deleteUser' : IDL.Func([IDL.Principal], [Result_8], []),
  'generatePaymentLink' : IDL.Func([IDL.Nat, IDL.Nat], [Result_10], []),
  'getActivityLogs' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ActivityLog)],
      ['query'],
    ),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getCourseCategories' : IDL.Func([], [IDL.Vec(CourseCategory)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getEmiInstallments' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(EmiInstallment)],
      ['query'],
    ),
  'getEmiReport' : IDL.Func([Timestamp, Timestamp], [EmiReport], ['query']),
  'getFollowUps' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(FollowUp)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getLeadReport' : IDL.Func([Timestamp, Timestamp], [LeadReport], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'getPayments' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Payment)], ['query']),
  'getReceipt' : IDL.Func([IDL.Nat], [IDL.Opt(Receipt)], ['query']),
  'getReceipts' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Receipt)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getRevenueReport' : IDL.Func(
      [Timestamp, Timestamp],
      [RevenueReport],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [AppSettings], ['query']),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'markEmiPaid' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [Result_9], []),
  'sendEmiReminder' : IDL.Func([IDL.Nat], [Result_8], []),
  'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'transferLead' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Principal], [Result_4], []),
  'updateCourse' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Bool,
      ],
      [Result_7],
      [],
    ),
  'updateCourseCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [Result_6],
      [],
    ),
  'updateFollowUp' : IDL.Func(
      [IDL.Nat, IDL.Text, Timestamp, IDL.Opt(Timestamp)],
      [Result_5],
      [],
    ),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Result_4],
      [],
    ),
  'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [Result_4], []),
  'updateSettings' : IDL.Func([AppSettings], [Result_3], []),
  'updateStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'updateTeam' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Principal), IDL.Text],
      [Result_1],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, Role], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'totalFee' : IDL.Nat,
    'emiOptions' : IDL.Vec(IDL.Nat),
  });
  const Result_7 = IDL.Variant({ 'ok' : Course, 'err' : IDL.Text });
  const UserId = IDL.Principal;
  const CourseCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : UserId,
    'description' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : CourseCategory, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const FollowUp = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'reminderDate' : IDL.Opt(Timestamp),
    'leadId' : IDL.Nat,
    'notes' : IDL.Text,
    'nextFollowUpDate' : Timestamp,
  });
  const Result_5 = IDL.Variant({ 'ok' : FollowUp, 'err' : IDL.Text });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'dropped' : IDL.Null,
    'followUp' : IDL.Null,
    'converted' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'assignedTo' : IDL.Opt(UserId),
    'source' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
    'courseId' : IDL.Nat,
  });
  const Result_4 = IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'online' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'studentId' : IDL.Nat,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'confirmedAt' : IDL.Opt(Timestamp),
    'confirmedBy' : IDL.Opt(UserId),
    'paymentLink' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const Result_11 = IDL.Variant({ 'ok' : Payment, 'err' : IDL.Text });
  const ReminderTargetType = IDL.Variant({
    'emi' : IDL.Null,
    'followUp' : IDL.Null,
    'payment' : IDL.Null,
  });
  const ReminderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'sent' : IDL.Null,
    'failed' : IDL.Null,
  });
  const ReminderRecipientType = IDL.Variant({
    'all' : IDL.Null,
    'teamHead' : IDL.Null,
    'admin' : IDL.Null,
    'student' : IDL.Null,
    'counselor' : IDL.Null,
  });
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReminderStatus,
    'sentAt' : IDL.Opt(Timestamp),
    'message' : IDL.Text,
    'targetType' : ReminderTargetType,
    'targetId' : IDL.Nat,
    'recipientType' : ReminderRecipientType,
    'scheduledAt' : Timestamp,
  });
  const Result_12 = IDL.Variant({ 'ok' : Reminder, 'err' : IDL.Text });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'headId' : IDL.Opt(UserId),
  });
  const Result_1 = IDL.Variant({ 'ok' : Team, 'err' : IDL.Text });
  const StudentStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const PaymentType = IDL.Variant({ 'emi' : IDL.Null, 'full' : IDL.Null });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'status' : StudentStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'totalFee' : IDL.Nat,
    'leadId' : IDL.Opt(IDL.Nat),
    'assignedCounselor' : IDL.Opt(UserId),
    'enrolledAt' : Timestamp,
    'paymentType' : PaymentType,
    'phone' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
    'paidAmount' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ActivityLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'userId' : UserId,
    'entityId' : IDL.Opt(IDL.Nat),
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const Role = IDL.Variant({
    'accountant' : IDL.Null,
    'teamHead' : IDL.Null,
    'admin' : IDL.Null,
    'counselor' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'teamId' : IDL.Opt(IDL.Nat),
  });
  const EmiStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'overdue' : IDL.Null,
  });
  const EmiInstallment = IDL.Record({
    'id' : IDL.Nat,
    'status' : EmiStatus,
    'studentId' : IDL.Nat,
    'installmentNumber' : IDL.Nat,
    'dueDate' : Timestamp,
    'paidDate' : IDL.Opt(Timestamp),
    'paymentId' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'convertedStudents' : IDL.Nat,
    'recentActivities' : IDL.Vec(ActivityLog),
    'totalLeads' : IDL.Nat,
    'overduePayments' : IDL.Nat,
    'upcomingEmi' : IDL.Vec(EmiInstallment),
    'pendingEmi' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'upcomingFollowUps' : IDL.Vec(FollowUp),
  });
  const EmiReport = IDL.Record({
    'overdueAmount' : IDL.Nat,
    'pending' : IDL.Nat,
    'paid' : IDL.Nat,
    'overdue' : IDL.Nat,
    'totalInstallments' : IDL.Nat,
  });
  const LeadReport = IDL.Record({
    'dropped' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'byStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'converted' : IDL.Nat,
  });
  const Receipt = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'generatedAt' : Timestamp,
    'generatedBy' : UserId,
    'paymentId' : IDL.Nat,
    'amount' : IDL.Nat,
    'receiptNumber' : IDL.Text,
  });
  const RevenueReport = IDL.Record({
    'emiRevenue' : IDL.Nat,
    'fullPayRevenue' : IDL.Nat,
    'confirmedPayments' : IDL.Vec(Payment),
    'totalRevenue' : IDL.Nat,
  });
  const AppSettings = IDL.Record({
    'companyEmail' : IDL.Text,
    'whatsappApiKey' : IDL.Text,
    'smtpHost' : IDL.Text,
    'smtpPort' : IDL.Nat,
    'smtpUser' : IDL.Text,
    'logoUrl' : IDL.Text,
    'smsApiKey' : IDL.Text,
    'companyName' : IDL.Text,
    'companyPhone' : IDL.Text,
    'paymentBaseUrl' : IDL.Text,
  });
  const Result_9 = IDL.Variant({ 'ok' : EmiInstallment, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : AppSettings, 'err' : IDL.Text });
  
  return IDL.Service({
    'addCourse' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Nat), IDL.Text],
        [Result_7],
        [],
      ),
    'addCourseCategory' : IDL.Func([IDL.Text, IDL.Text], [Result_6], []),
    'addFollowUp' : IDL.Func(
        [IDL.Nat, IDL.Text, Timestamp, IDL.Opt(Timestamp)],
        [Result_5],
        [],
      ),
    'addLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Result_4],
        [],
      ),
    'addPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentMethod, IDL.Opt(IDL.Text)],
        [Result_11],
        [],
      ),
    'addReminder' : IDL.Func(
        [ReminderTargetType, IDL.Nat, IDL.Text, Timestamp],
        [Result_12],
        [],
      ),
    'addTeam' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [Result_1],
        [],
      ),
    'assignCourse' : IDL.Func([IDL.Nat, IDL.Nat], [Result_2], []),
    'assignLead' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Principal], [Result_4], []),
    'assignTeamHead' : IDL.Func([IDL.Nat, IDL.Principal], [Result_1], []),
    'confirmPayment' : IDL.Func([IDL.Nat], [Result_11], []),
    'convertLeadToStudent' : IDL.Func(
        [IDL.Nat, PaymentType, IDL.Opt(IDL.Nat)],
        [Result_2],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteCourseCategory' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteFollowUp' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteLead' : IDL.Func([IDL.Nat], [Result_8], []),
    'deletePayment' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteTeam' : IDL.Func([IDL.Nat], [Result_8], []),
    'deleteUser' : IDL.Func([IDL.Principal], [Result_8], []),
    'generatePaymentLink' : IDL.Func([IDL.Nat, IDL.Nat], [Result_10], []),
    'getActivityLogs' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getCourseCategories' : IDL.Func([], [IDL.Vec(CourseCategory)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getEmiInstallments' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(EmiInstallment)],
        ['query'],
      ),
    'getEmiReport' : IDL.Func([Timestamp, Timestamp], [EmiReport], ['query']),
    'getFollowUps' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getLeadReport' : IDL.Func([Timestamp, Timestamp], [LeadReport], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'getPayments' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Payment)], ['query']),
    'getReceipt' : IDL.Func([IDL.Nat], [IDL.Opt(Receipt)], ['query']),
    'getReceipts' : IDL.Func([IDL.Opt(IDL.Nat)], [IDL.Vec(Receipt)], ['query']),
    'getReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getRevenueReport' : IDL.Func(
        [Timestamp, Timestamp],
        [RevenueReport],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [AppSettings], ['query']),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'markEmiPaid' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Nat)], [Result_9], []),
    'sendEmiReminder' : IDL.Func([IDL.Nat], [Result_8], []),
    'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'transferLead' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Principal],
        [Result_4],
        [],
      ),
    'updateCourse' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Bool,
        ],
        [Result_7],
        [],
      ),
    'updateCourseCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [Result_6],
        [],
      ),
    'updateFollowUp' : IDL.Func(
        [IDL.Nat, IDL.Text, Timestamp, IDL.Opt(Timestamp)],
        [Result_5],
        [],
      ),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Result_4],
        [],
      ),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [Result_4], []),
    'updateSettings' : IDL.Func([AppSettings], [Result_3], []),
    'updateStudent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'updateTeam' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Principal), IDL.Text],
        [Result_1],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, Role], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };