/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'id' : bigint,
  'action' : string,
  'userId' : UserId,
  'entityId' : [] | [bigint],
  'timestamp' : Timestamp,
  'details' : string,
  'entityType' : string,
}
export interface AppSettings {
  'companyEmail' : string,
  'whatsappApiKey' : string,
  'smtpHost' : string,
  'smtpPort' : bigint,
  'smtpUser' : string,
  'logoUrl' : string,
  'smsApiKey' : string,
  'companyName' : string,
  'companyPhone' : string,
  'paymentBaseUrl' : string,
}
export interface Course {
  'id' : bigint,
  'categoryId' : bigint,
  'duration' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'totalFee' : bigint,
  'emiOptions' : Array<bigint>,
}
export interface CourseCategory {
  'id' : bigint,
  'name' : string,
  'createdBy' : UserId,
  'description' : string,
}
export interface DashboardStats {
  'convertedStudents' : bigint,
  'recentActivities' : Array<ActivityLog>,
  'totalLeads' : bigint,
  'overduePayments' : bigint,
  'upcomingEmi' : Array<EmiInstallment>,
  'pendingEmi' : bigint,
  'totalRevenue' : bigint,
  'upcomingFollowUps' : Array<FollowUp>,
}
export interface EmiInstallment {
  'id' : bigint,
  'status' : EmiStatus,
  'studentId' : bigint,
  'installmentNumber' : bigint,
  'dueDate' : Timestamp,
  'paidDate' : [] | [Timestamp],
  'paymentId' : [] | [bigint],
  'amount' : bigint,
}
export interface EmiReport {
  'overdueAmount' : bigint,
  'pending' : bigint,
  'paid' : bigint,
  'overdue' : bigint,
  'totalInstallments' : bigint,
}
export type EmiStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'overdue' : null };
export interface FollowUp {
  'id' : bigint,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'reminderDate' : [] | [Timestamp],
  'leadId' : bigint,
  'notes' : string,
  'nextFollowUpDate' : Timestamp,
}
export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'assignedTo' : [] | [UserId],
  'source' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'email' : string,
  'updatedAt' : Timestamp,
  'notes' : string,
  'phone' : string,
  'teamId' : [] | [bigint],
  'courseId' : bigint,
}
export interface LeadReport {
  'dropped' : bigint,
  'totalLeads' : bigint,
  'byStatus' : Array<[string, bigint]>,
  'converted' : bigint,
}
export type LeadStatus = { 'new' : null } |
  { 'dropped' : null } |
  { 'followUp' : null } |
  { 'converted' : null };
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'studentId' : bigint,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'confirmedAt' : [] | [Timestamp],
  'confirmedBy' : [] | [UserId],
  'paymentLink' : [] | [string],
  'amount' : bigint,
  'transactionId' : [] | [string],
}
export type PaymentMethod = { 'cash' : null } |
  { 'bankTransfer' : null } |
  { 'online' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export type PaymentType = { 'emi' : null } |
  { 'full' : null };
export interface Receipt {
  'id' : bigint,
  'studentId' : bigint,
  'generatedAt' : Timestamp,
  'generatedBy' : UserId,
  'paymentId' : bigint,
  'amount' : bigint,
  'receiptNumber' : string,
}
export interface Reminder {
  'id' : bigint,
  'status' : ReminderStatus,
  'sentAt' : [] | [Timestamp],
  'message' : string,
  'targetType' : ReminderTargetType,
  'targetId' : bigint,
  'recipientType' : ReminderRecipientType,
  'scheduledAt' : Timestamp,
}
export type ReminderRecipientType = { 'all' : null } |
  { 'teamHead' : null } |
  { 'admin' : null } |
  { 'student' : null } |
  { 'counselor' : null };
export type ReminderStatus = { 'pending' : null } |
  { 'sent' : null } |
  { 'failed' : null };
export type ReminderTargetType = { 'emi' : null } |
  { 'followUp' : null } |
  { 'payment' : null };
export type Result = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_1 = { 'ok' : Team } |
  { 'err' : string };
export type Result_10 = { 'ok' : string } |
  { 'err' : string };
export type Result_11 = { 'ok' : Payment } |
  { 'err' : string };
export type Result_12 = { 'ok' : Reminder } |
  { 'err' : string };
export type Result_2 = { 'ok' : Student } |
  { 'err' : string };
export type Result_3 = { 'ok' : AppSettings } |
  { 'err' : string };
export type Result_4 = { 'ok' : Lead } |
  { 'err' : string };
export type Result_5 = { 'ok' : FollowUp } |
  { 'err' : string };
export type Result_6 = { 'ok' : CourseCategory } |
  { 'err' : string };
export type Result_7 = { 'ok' : Course } |
  { 'err' : string };
export type Result_8 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_9 = { 'ok' : EmiInstallment } |
  { 'err' : string };
export interface RevenueReport {
  'emiRevenue' : bigint,
  'fullPayRevenue' : bigint,
  'confirmedPayments' : Array<Payment>,
  'totalRevenue' : bigint,
}
export type Role = { 'accountant' : null } |
  { 'teamHead' : null } |
  { 'admin' : null } |
  { 'counselor' : null };
export interface Student {
  'id' : bigint,
  'status' : StudentStatus,
  'name' : string,
  'email' : string,
  'totalFee' : bigint,
  'leadId' : [] | [bigint],
  'assignedCounselor' : [] | [UserId],
  'enrolledAt' : Timestamp,
  'paymentType' : PaymentType,
  'phone' : string,
  'teamId' : [] | [bigint],
  'paidAmount' : bigint,
  'courseId' : bigint,
}
export type StudentStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'inactive' : null };
export interface Team {
  'id' : bigint,
  'categoryId' : [] | [bigint],
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'headId' : [] | [UserId],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'teamId' : [] | [bigint],
}
export interface _SERVICE {
  'addCourse' : ActorMethod<
    [string, bigint, bigint, string, Array<bigint>, string],
    Result_7
  >,
  'addCourseCategory' : ActorMethod<[string, string], Result_6>,
  'addFollowUp' : ActorMethod<
    [bigint, string, Timestamp, [] | [Timestamp]],
    Result_5
  >,
  'addLead' : ActorMethod<
    [string, string, string, bigint, string, string],
    Result_4
  >,
  'addPayment' : ActorMethod<
    [bigint, bigint, PaymentMethod, [] | [string]],
    Result_11
  >,
  'addReminder' : ActorMethod<
    [ReminderTargetType, bigint, string, Timestamp],
    Result_12
  >,
  'addTeam' : ActorMethod<[string, [] | [bigint], string], Result_1>,
  'assignCourse' : ActorMethod<[bigint, bigint], Result_2>,
  'assignLead' : ActorMethod<[bigint, bigint, Principal], Result_4>,
  'assignTeamHead' : ActorMethod<[bigint, Principal], Result_1>,
  'confirmPayment' : ActorMethod<[bigint], Result_11>,
  'convertLeadToStudent' : ActorMethod<
    [bigint, PaymentType, [] | [bigint]],
    Result_2
  >,
  'deleteCourse' : ActorMethod<[bigint], Result_8>,
  'deleteCourseCategory' : ActorMethod<[bigint], Result_8>,
  'deleteFollowUp' : ActorMethod<[bigint], Result_8>,
  'deleteLead' : ActorMethod<[bigint], Result_8>,
  'deletePayment' : ActorMethod<[bigint], Result_8>,
  'deleteReminder' : ActorMethod<[bigint], Result_8>,
  'deleteStudent' : ActorMethod<[bigint], Result_8>,
  'deleteTeam' : ActorMethod<[bigint], Result_8>,
  'deleteUser' : ActorMethod<[Principal], Result_8>,
  'generatePaymentLink' : ActorMethod<[bigint, bigint], Result_10>,
  'getActivityLogs' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ActivityLog>
  >,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getCourseCategories' : ActorMethod<[], Array<CourseCategory>>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getEmiInstallments' : ActorMethod<[[] | [bigint]], Array<EmiInstallment>>,
  'getEmiReport' : ActorMethod<[Timestamp, Timestamp], EmiReport>,
  'getFollowUps' : ActorMethod<[[] | [bigint]], Array<FollowUp>>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getLeadReport' : ActorMethod<[Timestamp, Timestamp], LeadReport>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'getPayments' : ActorMethod<[[] | [bigint]], Array<Payment>>,
  'getReceipt' : ActorMethod<[bigint], [] | [Receipt]>,
  'getReceipts' : ActorMethod<[[] | [bigint]], Array<Receipt>>,
  'getReminders' : ActorMethod<[], Array<Reminder>>,
  'getRevenueReport' : ActorMethod<[Timestamp, Timestamp], RevenueReport>,
  'getSettings' : ActorMethod<[], AppSettings>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getStudents' : ActorMethod<[], Array<Student>>,
  'getTeam' : ActorMethod<[bigint], [] | [Team]>,
  'getTeams' : ActorMethod<[], Array<Team>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'markEmiPaid' : ActorMethod<[bigint, [] | [bigint]], Result_9>,
  'sendEmiReminder' : ActorMethod<[bigint], Result_8>,
  'setUserProfile' : ActorMethod<[string, string], Result>,
  'transferLead' : ActorMethod<[bigint, bigint, Principal], Result_4>,
  'updateCourse' : ActorMethod<
    [bigint, string, bigint, bigint, string, Array<bigint>, string, boolean],
    Result_7
  >,
  'updateCourseCategory' : ActorMethod<[bigint, string, string], Result_6>,
  'updateFollowUp' : ActorMethod<
    [bigint, string, Timestamp, [] | [Timestamp]],
    Result_5
  >,
  'updateLead' : ActorMethod<
    [bigint, string, string, string, bigint, string, string],
    Result_4
  >,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], Result_4>,
  'updateSettings' : ActorMethod<[AppSettings], Result_3>,
  'updateStudent' : ActorMethod<[bigint, string, string, string], Result_2>,
  'updateTeam' : ActorMethod<
    [bigint, string, [] | [bigint], [] | [Principal], string],
    Result_1
  >,
  'updateUserRole' : ActorMethod<[Principal, Role], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];