/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
};
export type Result_5 = {
    __kind__: "ok";
    ok: FollowUp;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Team;
} | {
    __kind__: "err";
    err: string;
};
export interface RevenueReport {
    emiRevenue: bigint;
    fullPayRevenue: bigint;
    confirmedPayments: Array<Payment>;
    totalRevenue: bigint;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Lead;
} | {
    __kind__: "err";
    err: string;
};
export type Result_11 = {
    __kind__: "ok";
    ok: Payment;
} | {
    __kind__: "err";
    err: string;
};
export interface Receipt {
    id: bigint;
    studentId: bigint;
    generatedAt: Timestamp;
    generatedBy: UserId;
    paymentId: bigint;
    amount: bigint;
    receiptNumber: string;
}
export interface Reminder {
    id: bigint;
    status: ReminderStatus;
    sentAt?: Timestamp;
    message: string;
    targetType: ReminderTargetType;
    targetId: bigint;
    recipientType: ReminderRecipientType;
    scheduledAt: Timestamp;
}
export interface LeadReport {
    dropped: bigint;
    totalLeads: bigint;
    byStatus: Array<[string, bigint]>;
    converted: bigint;
}
export interface Lead {
    id: bigint;
    status: LeadStatus;
    assignedTo?: UserId;
    source: string;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    email: string;
    updatedAt: Timestamp;
    notes: string;
    phone: string;
    teamId?: bigint;
    courseId: bigint;
}
export interface Course {
    id: bigint;
    categoryId: bigint;
    duration: string;
    name: string;
    description: string;
    isActive: boolean;
    totalFee: bigint;
    emiOptions: Array<bigint>;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Course;
} | {
    __kind__: "err";
    err: string;
};
export interface EmiInstallment {
    id: bigint;
    status: EmiStatus;
    studentId: bigint;
    installmentNumber: bigint;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    paymentId?: bigint;
    amount: bigint;
}
export interface Student {
    id: bigint;
    status: StudentStatus;
    name: string;
    email: string;
    totalFee: bigint;
    leadId?: bigint;
    assignedCounselor?: UserId;
    enrolledAt: Timestamp;
    paymentType: PaymentType;
    phone: string;
    teamId?: bigint;
    paidAmount: bigint;
    courseId: bigint;
}
export interface Team {
    id: bigint;
    categoryId?: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    headId?: UserId;
}
export type Result_6 = {
    __kind__: "ok";
    ok: CourseCategory;
} | {
    __kind__: "err";
    err: string;
};
export interface CourseCategory {
    id: bigint;
    name: string;
    createdBy: UserId;
    description: string;
}
export interface ActivityLog {
    id: bigint;
    action: string;
    userId: UserId;
    entityId?: bigint;
    timestamp: Timestamp;
    details: string;
    entityType: string;
}
export type Result_12 = {
    __kind__: "ok";
    ok: Reminder;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: EmiInstallment;
} | {
    __kind__: "err";
    err: string;
};
export interface Payment {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    studentId: bigint;
    createdAt: Timestamp;
    createdBy: UserId;
    confirmedAt?: Timestamp;
    confirmedBy?: UserId;
    paymentLink?: string;
    amount: bigint;
    transactionId?: string;
}
export interface DashboardStats {
    convertedStudents: bigint;
    recentActivities: Array<ActivityLog>;
    totalLeads: bigint;
    overduePayments: bigint;
    upcomingEmi: Array<EmiInstallment>;
    pendingEmi: bigint;
    totalRevenue: bigint;
    upcomingFollowUps: Array<FollowUp>;
}
export interface AppSettings {
    companyEmail: string;
    whatsappApiKey: string;
    smtpHost: string;
    smtpPort: bigint;
    smtpUser: string;
    logoUrl: string;
    smsApiKey: string;
    companyName: string;
    companyPhone: string;
    paymentBaseUrl: string;
}
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: AppSettings;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface FollowUp {
    id: bigint;
    createdAt: Timestamp;
    createdBy: UserId;
    reminderDate?: Timestamp;
    leadId: bigint;
    notes: string;
    nextFollowUpDate: Timestamp;
}
export interface UserProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    teamId?: bigint;
}
export interface EmiReport {
    overdueAmount: bigint;
    pending: bigint;
    paid: bigint;
    overdue: bigint;
    totalInstallments: bigint;
}
export enum EmiStatus {
    pending = "pending",
    paid = "paid",
    overdue = "overdue"
}
export enum LeadStatus {
    new_ = "new",
    dropped = "dropped",
    followUp = "followUp",
    converted = "converted"
}
export enum PaymentMethod {
    cash = "cash",
    bankTransfer = "bankTransfer",
    online = "online"
}
export enum PaymentStatus {
    pending = "pending",
    rejected = "rejected",
    confirmed = "confirmed"
}
export enum PaymentType {
    emi = "emi",
    full = "full"
}
export enum ReminderRecipientType {
    all = "all",
    teamHead = "teamHead",
    admin = "admin",
    student = "student",
    counselor = "counselor"
}
export enum ReminderStatus {
    pending = "pending",
    sent = "sent",
    failed = "failed"
}
export enum ReminderTargetType {
    emi = "emi",
    followUp = "followUp",
    payment = "payment"
}
export enum Role {
    accountant = "accountant",
    teamHead = "teamHead",
    admin = "admin",
    counselor = "counselor"
}
export enum StudentStatus {
    active = "active",
    completed = "completed",
    inactive = "inactive"
}
export interface backendInterface {
    addCourse(name: string, categoryId: bigint, totalFee: bigint, duration: string, emiOptions: Array<bigint>, description: string): Promise<Result_7>;
    addCourseCategory(name: string, description: string): Promise<Result_6>;
    addFollowUp(leadId: bigint, notes: string, nextFollowUpDate: Timestamp, reminderDate: Timestamp | null): Promise<Result_5>;
    addLead(name: string, email: string, phone: string, courseId: bigint, source: string, notes: string): Promise<Result_4>;
    addPayment(studentId: bigint, amount: bigint, method: PaymentMethod, transactionId: string | null): Promise<Result_11>;
    addReminder(targetType: ReminderTargetType, targetId: bigint, message: string, scheduledAt: Timestamp): Promise<Result_12>;
    addTeam(name: string, categoryId: bigint | null, description: string): Promise<Result_1>;
    assignCourse(studentId: bigint, courseId: bigint): Promise<Result_2>;
    assignLead(leadId: bigint, teamId: bigint, counselorId: Principal): Promise<Result_4>;
    assignTeamHead(teamId: bigint, headId: Principal): Promise<Result_1>;
    confirmPayment(paymentId: bigint): Promise<Result_11>;
    convertLeadToStudent(leadId: bigint, paymentType: PaymentType, emiMonths: bigint | null): Promise<Result_2>;
    deleteCourse(id: bigint): Promise<Result_8>;
    deleteCourseCategory(id: bigint): Promise<Result_8>;
    deleteFollowUp(id: bigint): Promise<Result_8>;
    deleteLead(id: bigint): Promise<Result_8>;
    deletePayment(id: bigint): Promise<Result_8>;
    deleteReminder(id: bigint): Promise<Result_8>;
    deleteStudent(id: bigint): Promise<Result_8>;
    deleteTeam(id: bigint): Promise<Result_8>;
    deleteUser(userId: Principal): Promise<Result_8>;
    generatePaymentLink(studentId: bigint, amount: bigint): Promise<Result_10>;
    getActivityLogs(limit: bigint | null, offset: bigint | null): Promise<Array<ActivityLog>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCourse(id: bigint): Promise<Course | null>;
    getCourseCategories(): Promise<Array<CourseCategory>>;
    getCourses(): Promise<Array<Course>>;
    getDashboardStats(): Promise<DashboardStats>;
    getEmiInstallments(studentId: bigint | null): Promise<Array<EmiInstallment>>;
    getEmiReport(fromDate: Timestamp, toDate: Timestamp): Promise<EmiReport>;
    getFollowUps(leadId: bigint | null): Promise<Array<FollowUp>>;
    getLead(id: bigint): Promise<Lead | null>;
    getLeadReport(fromDate: Timestamp, toDate: Timestamp): Promise<LeadReport>;
    getLeads(): Promise<Array<Lead>>;
    getPayment(id: bigint): Promise<Payment | null>;
    getPayments(studentId: bigint | null): Promise<Array<Payment>>;
    getReceipt(id: bigint): Promise<Receipt | null>;
    getReceipts(studentId: bigint | null): Promise<Array<Receipt>>;
    getReminders(): Promise<Array<Reminder>>;
    getRevenueReport(fromDate: Timestamp, toDate: Timestamp): Promise<RevenueReport>;
    getSettings(): Promise<AppSettings>;
    getStudent(id: bigint): Promise<Student | null>;
    getStudents(): Promise<Array<Student>>;
    getTeam(id: bigint): Promise<Team | null>;
    getTeams(): Promise<Array<Team>>;
    getUserProfile(): Promise<UserProfile | null>;
    markEmiPaid(installmentId: bigint, paymentId: bigint | null): Promise<Result_9>;
    sendEmiReminder(installmentId: bigint): Promise<Result_8>;
    setUserProfile(name: string, email: string): Promise<Result>;
    transferLead(leadId: bigint, newTeamId: bigint, newCounselorId: Principal): Promise<Result_4>;
    updateCourse(id: bigint, name: string, categoryId: bigint, totalFee: bigint, duration: string, emiOptions: Array<bigint>, description: string, isActive: boolean): Promise<Result_7>;
    updateCourseCategory(id: bigint, name: string, description: string): Promise<Result_6>;
    updateFollowUp(id: bigint, notes: string, nextFollowUpDate: Timestamp, reminderDate: Timestamp | null): Promise<Result_5>;
    updateLead(id: bigint, name: string, email: string, phone: string, courseId: bigint, source: string, notes: string): Promise<Result_4>;
    updateLeadStatus(leadId: bigint, status: LeadStatus): Promise<Result_4>;
    updateSettings(settings: AppSettings): Promise<Result_3>;
    updateStudent(id: bigint, name: string, email: string, phone: string): Promise<Result_2>;
    updateTeam(id: bigint, name: string, categoryId: bigint | null, headId: Principal | null, description: string): Promise<Result_1>;
    updateUserRole(userId: Principal, role: Role): Promise<Result>;
}
import type { ActivityLog as _ActivityLog, AppSettings as _AppSettings, Course as _Course, CourseCategory as _CourseCategory, DashboardStats as _DashboardStats, EmiInstallment as _EmiInstallment, EmiStatus as _EmiStatus, FollowUp as _FollowUp, Lead as _Lead, LeadStatus as _LeadStatus, Payment as _Payment, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, PaymentType as _PaymentType, Receipt as _Receipt, Reminder as _Reminder, ReminderRecipientType as _ReminderRecipientType, ReminderStatus as _ReminderStatus, ReminderTargetType as _ReminderTargetType, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_11 as _Result_11, Result_12 as _Result_12, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, RevenueReport as _RevenueReport, Role as _Role, Student as _Student, StudentStatus as _StudentStatus, Team as _Team, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCourse(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: Array<bigint>, arg5: string): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCourseCategory(arg0: string, arg1: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourseCategory(arg0, arg1);
                return from_candid_Result_6_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourseCategory(arg0, arg1);
            return from_candid_Result_6_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFollowUp(arg0: bigint, arg1: string, arg2: Timestamp, arg3: Timestamp | null): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.addFollowUp(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_5_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFollowUp(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_5_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addLead(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPayment(arg0: bigint, arg1: bigint, arg2: PaymentMethod, arg3: string | null): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, arg1, to_candid_PaymentMethod_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_11_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, arg1, to_candid_PaymentMethod_n19(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n21(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_11_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReminder(arg0: ReminderTargetType, arg1: bigint, arg2: string, arg3: Timestamp): Promise<Result_12> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(to_candid_ReminderTargetType_n31(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return from_candid_Result_12_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(to_candid_ReminderTargetType_n31(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return from_candid_Result_12_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTeam(arg0: string, arg1: bigint | null, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCourse(arg0: bigint, arg1: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCourse(arg0, arg1);
                return from_candid_Result_2_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCourse(arg0, arg1);
            return from_candid_Result_2_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignLead(arg0: bigint, arg1: bigint, arg2: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.assignLead(arg0, arg1, arg2);
                return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignLead(arg0, arg1, arg2);
            return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignTeamHead(arg0: bigint, arg1: Principal): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTeamHead(arg0, arg1);
                return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTeamHead(arg0, arg1);
            return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async confirmPayment(arg0: bigint): Promise<Result_11> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmPayment(arg0);
                return from_candid_Result_11_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmPayment(arg0);
            return from_candid_Result_11_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async convertLeadToStudent(arg0: bigint, arg1: PaymentType, arg2: bigint | null): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.convertLeadToStudent(arg0, to_candid_PaymentType_n56(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_2_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertLeadToStudent(arg0, to_candid_PaymentType_n56(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_2_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCourse(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourse(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourse(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCourseCategory(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCourseCategory(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCourseCategory(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFollowUp(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLead(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePayment(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReminder(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStudent(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteTeam(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeam(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeam(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: Principal): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async generatePaymentLink(arg0: bigint, arg1: bigint): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePaymentLink(arg0, arg1);
                return from_candid_Result_10_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePaymentLink(arg0, arg1);
            return from_candid_Result_10_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogs(arg0: bigint | null, arg1: bigint | null): Promise<Array<ActivityLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: bigint): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseCategories(): Promise<Array<CourseCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseCategories();
            return result;
        }
    }
    async getCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourses();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmiInstallments(arg0: bigint | null): Promise<Array<EmiInstallment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmiInstallments(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmiInstallments(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmiReport(arg0: Timestamp, arg1: Timestamp): Promise<EmiReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmiReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmiReport(arg0, arg1);
            return result;
        }
    }
    async getFollowUps(arg0: bigint | null): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUps(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUps(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: bigint): Promise<Lead | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadReport(arg0: Timestamp, arg1: Timestamp): Promise<LeadReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadReport(arg0, arg1);
            return result;
        }
    }
    async getLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayments(arg0: bigint | null): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipt(arg0: bigint): Promise<Receipt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipt(arg0);
                return from_candid_opt_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipt(arg0);
            return from_candid_opt_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipts(arg0: bigint | null): Promise<Array<Receipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipts(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipts(to_candid_opt_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRevenueReport(arg0: Timestamp, arg1: Timestamp): Promise<RevenueReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueReport(arg0, arg1);
                return from_candid_RevenueReport_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueReport(arg0, arg1);
            return from_candid_RevenueReport_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AppSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getStudent(arg0: bigint): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudents();
                return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudents();
            return from_candid_vec_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: bigint): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeams();
                return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeams();
            return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async markEmiPaid(arg0: bigint, arg1: bigint | null): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.markEmiPaid(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_9_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markEmiPaid(arg0, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_9_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendEmiReminder(arg0: bigint): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.sendEmiReminder(arg0);
                return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendEmiReminder(arg0);
            return from_candid_Result_8_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserProfile(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0, arg1);
                return from_candid_Result_n94(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0, arg1);
            return from_candid_Result_n94(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferLead(arg0: bigint, arg1: bigint, arg2: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.transferLead(arg0, arg1, arg2);
                return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferLead(arg0, arg1, arg2);
            return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCourse(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: Array<bigint>, arg6: string, arg7: boolean): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Result_7_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCourseCategory(arg0: bigint, arg1: string, arg2: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourseCategory(arg0, arg1, arg2);
                return from_candid_Result_6_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourseCategory(arg0, arg1, arg2);
            return from_candid_Result_6_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFollowUp(arg0: bigint, arg1: string, arg2: Timestamp, arg3: Timestamp | null): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUp(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_5_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUp(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_5_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLeadStatus(arg0: bigint, arg1: LeadStatus): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n96(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n96(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_4_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: AppSettings): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return from_candid_Result_3_n98(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return from_candid_Result_3_n98(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3);
                return from_candid_Result_2_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1, arg2, arg3);
            return from_candid_Result_2_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTeam(arg0: bigint, arg1: string, arg2: bigint | null, arg3: Principal | null, arg4: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(arg0, arg1, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n100(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(arg0, arg1, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n100(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: Principal, arg1: Role): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_Role_n101(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n94(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_Role_n101(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n94(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityLog_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLog): ActivityLog {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardStats_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_EmiInstallment_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmiInstallment): EmiInstallment {
    return from_candid_record_n75(_uploadFile, _downloadFile, value);
}
function from_candid_EmiStatus_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmiStatus): EmiStatus {
    return from_candid_variant_n77(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUp_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUp): FollowUp {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ReminderRecipientType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderRecipientType): ReminderRecipientType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ReminderStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderStatus): ReminderStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ReminderTargetType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderTargetType): ReminderTargetType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Reminder_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reminder): Reminder {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result_10_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Result_11_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_11): Result_11 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_12_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_12): Result_12 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n93(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function from_candid_RevenueReport_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RevenueReport): RevenueReport {
    return from_candid_record_n86(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_StudentStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentStatus): StudentStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Student_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Student {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lead]): Lead | null {
    return value.length === 0 ? null : from_candid_Lead_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Receipt]): Receipt | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : from_candid_Student_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : from_candid_Team_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n66(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    assignedTo: [] | [_UserId];
    source: string;
    name: string;
    createdAt: _Timestamp;
    createdBy: _UserId;
    email: string;
    updatedAt: _Timestamp;
    notes: string;
    phone: string;
    teamId: [] | [bigint];
    courseId: bigint;
}): {
    id: bigint;
    status: LeadStatus;
    assignedTo?: UserId;
    source: string;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    email: string;
    updatedAt: Timestamp;
    notes: string;
    phone: string;
    teamId?: bigint;
    courseId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n15(_uploadFile, _downloadFile, value.status),
        assignedTo: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedTo)),
        source: value.source,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        updatedAt: value.updatedAt,
        notes: value.notes,
        phone: value.phone,
        teamId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.teamId)),
        courseId: value.courseId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    method: _PaymentMethod;
    studentId: bigint;
    createdAt: _Timestamp;
    createdBy: _UserId;
    confirmedAt: [] | [_Timestamp];
    confirmedBy: [] | [_UserId];
    paymentLink: [] | [string];
    amount: bigint;
    transactionId: [] | [string];
}): {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    studentId: bigint;
    createdAt: Timestamp;
    createdBy: UserId;
    confirmedAt?: Timestamp;
    confirmedBy?: UserId;
    paymentLink?: string;
    amount: bigint;
    transactionId?: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n26(_uploadFile, _downloadFile, value.status),
        method: from_candid_PaymentMethod_n28(_uploadFile, _downloadFile, value.method),
        studentId: value.studentId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        confirmedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.confirmedAt)),
        confirmedBy: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.confirmedBy)),
        paymentLink: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.paymentLink)),
        amount: value.amount,
        transactionId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ReminderStatus;
    sentAt: [] | [_Timestamp];
    message: string;
    targetType: _ReminderTargetType;
    targetId: bigint;
    recipientType: _ReminderRecipientType;
    scheduledAt: _Timestamp;
}): {
    id: bigint;
    status: ReminderStatus;
    sentAt?: Timestamp;
    message: string;
    targetType: ReminderTargetType;
    targetId: bigint;
    recipientType: ReminderRecipientType;
    scheduledAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ReminderStatus_n37(_uploadFile, _downloadFile, value.status),
        sentAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.sentAt)),
        message: value.message,
        targetType: from_candid_ReminderTargetType_n39(_uploadFile, _downloadFile, value.targetType),
        targetId: value.targetId,
        recipientType: from_candid_ReminderRecipientType_n41(_uploadFile, _downloadFile, value.recipientType),
        scheduledAt: value.scheduledAt
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    categoryId: [] | [bigint];
    name: string;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    headId: [] | [_UserId];
}): {
    id: bigint;
    categoryId?: bigint;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    headId?: UserId;
} {
    return {
        id: value.id,
        categoryId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.categoryId)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        headId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.headId))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _StudentStatus;
    name: string;
    email: string;
    totalFee: bigint;
    leadId: [] | [bigint];
    assignedCounselor: [] | [_UserId];
    enrolledAt: _Timestamp;
    paymentType: _PaymentType;
    phone: string;
    teamId: [] | [bigint];
    paidAmount: bigint;
    courseId: bigint;
}): {
    id: bigint;
    status: StudentStatus;
    name: string;
    email: string;
    totalFee: bigint;
    leadId?: bigint;
    assignedCounselor?: UserId;
    enrolledAt: Timestamp;
    paymentType: PaymentType;
    phone: string;
    teamId?: bigint;
    paidAmount: bigint;
    courseId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_StudentStatus_n52(_uploadFile, _downloadFile, value.status),
        name: value.name,
        email: value.email,
        totalFee: value.totalFee,
        leadId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.leadId)),
        assignedCounselor: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.assignedCounselor)),
        enrolledAt: value.enrolledAt,
        paymentType: from_candid_PaymentType_n54(_uploadFile, _downloadFile, value.paymentType),
        phone: value.phone,
        teamId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.teamId)),
        paidAmount: value.paidAmount,
        courseId: value.courseId
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    userId: _UserId;
    entityId: [] | [bigint];
    timestamp: _Timestamp;
    details: string;
    entityType: string;
}): {
    id: bigint;
    action: string;
    userId: UserId;
    entityId?: bigint;
    timestamp: Timestamp;
    details: string;
    entityType: string;
} {
    return {
        id: value.id,
        action: value.action,
        userId: value.userId,
        entityId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.entityId)),
        timestamp: value.timestamp,
        details: value.details,
        entityType: value.entityType
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    teamId: [] | [bigint];
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    teamId?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n68(_uploadFile, _downloadFile, value.role),
        email: value.email,
        teamId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.teamId))
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    convertedStudents: bigint;
    recentActivities: Array<_ActivityLog>;
    totalLeads: bigint;
    overduePayments: bigint;
    upcomingEmi: Array<_EmiInstallment>;
    pendingEmi: bigint;
    totalRevenue: bigint;
    upcomingFollowUps: Array<_FollowUp>;
}): {
    convertedStudents: bigint;
    recentActivities: Array<ActivityLog>;
    totalLeads: bigint;
    overduePayments: bigint;
    upcomingEmi: Array<EmiInstallment>;
    pendingEmi: bigint;
    totalRevenue: bigint;
    upcomingFollowUps: Array<FollowUp>;
} {
    return {
        convertedStudents: value.convertedStudents,
        recentActivities: from_candid_vec_n62(_uploadFile, _downloadFile, value.recentActivities),
        totalLeads: value.totalLeads,
        overduePayments: value.overduePayments,
        upcomingEmi: from_candid_vec_n73(_uploadFile, _downloadFile, value.upcomingEmi),
        pendingEmi: value.pendingEmi,
        totalRevenue: value.totalRevenue,
        upcomingFollowUps: from_candid_vec_n78(_uploadFile, _downloadFile, value.upcomingFollowUps)
    };
}
function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EmiStatus;
    studentId: bigint;
    installmentNumber: bigint;
    dueDate: _Timestamp;
    paidDate: [] | [_Timestamp];
    paymentId: [] | [bigint];
    amount: bigint;
}): {
    id: bigint;
    status: EmiStatus;
    studentId: bigint;
    installmentNumber: bigint;
    dueDate: Timestamp;
    paidDate?: Timestamp;
    paymentId?: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_EmiStatus_n76(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        installmentNumber: value.installmentNumber,
        dueDate: value.dueDate,
        paidDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.paidDate)),
        paymentId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.paymentId)),
        amount: value.amount
    };
}
function from_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emiRevenue: bigint;
    fullPayRevenue: bigint;
    confirmedPayments: Array<_Payment>;
    totalRevenue: bigint;
}): {
    emiRevenue: bigint;
    fullPayRevenue: bigint;
    confirmedPayments: Array<Payment>;
    totalRevenue: bigint;
} {
    return {
        emiRevenue: value.emiRevenue,
        fullPayRevenue: value.fullPayRevenue,
        confirmedPayments: from_candid_vec_n82(_uploadFile, _downloadFile, value.confirmedPayments),
        totalRevenue: value.totalRevenue
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: _Timestamp;
    createdBy: _UserId;
    reminderDate: [] | [_Timestamp];
    leadId: bigint;
    notes: string;
    nextFollowUpDate: _Timestamp;
}): {
    id: bigint;
    createdAt: Timestamp;
    createdBy: UserId;
    reminderDate?: Timestamp;
    leadId: bigint;
    notes: string;
    nextFollowUpDate: Timestamp;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        reminderDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.reminderDate)),
        leadId: value.leadId,
        notes: value.notes,
        nextFollowUpDate: value.nextFollowUpDate
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Lead;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Lead;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Lead_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    dropped: null;
} | {
    followUp: null;
} | {
    converted: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "dropped" in value ? LeadStatus.dropped : "followUp" in value ? LeadStatus.followUp : "converted" in value ? LeadStatus.converted : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Course;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Course;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Payment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Payment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Payment_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    confirmed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "rejected" in value ? PaymentStatus.rejected : "confirmed" in value ? PaymentStatus.confirmed : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    bankTransfer: null;
} | {
    online: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "bankTransfer" in value ? PaymentMethod.bankTransfer : "online" in value ? PaymentMethod.online : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Reminder;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Reminder;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Reminder_n35(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sent: null;
} | {
    failed: null;
}): ReminderStatus {
    return "pending" in value ? ReminderStatus.pending : "sent" in value ? ReminderStatus.sent : "failed" in value ? ReminderStatus.failed : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CourseCategory;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CourseCategory;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emi: null;
} | {
    followUp: null;
} | {
    payment: null;
}): ReminderTargetType {
    return "emi" in value ? ReminderTargetType.emi : "followUp" in value ? ReminderTargetType.followUp : "payment" in value ? ReminderTargetType.payment : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    teamHead: null;
} | {
    admin: null;
} | {
    student: null;
} | {
    counselor: null;
}): ReminderRecipientType {
    return "all" in value ? ReminderRecipientType.all : "teamHead" in value ? ReminderRecipientType.teamHead : "admin" in value ? ReminderRecipientType.admin : "student" in value ? ReminderRecipientType.student : "counselor" in value ? ReminderRecipientType.counselor : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Team;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Team;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Team_n46(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Student;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Student_n50(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    inactive: null;
}): StudentStatus {
    return "active" in value ? StudentStatus.active : "completed" in value ? StudentStatus.completed : "inactive" in value ? StudentStatus.inactive : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emi: null;
} | {
    full: null;
}): PaymentType {
    return "emi" in value ? PaymentType.emi : "full" in value ? PaymentType.full : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountant: null;
} | {
    teamHead: null;
} | {
    admin: null;
} | {
    counselor: null;
}): Role {
    return "accountant" in value ? Role.accountant : "teamHead" in value ? Role.teamHead : "admin" in value ? Role.admin : "counselor" in value ? Role.counselor : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FollowUp;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FollowUp;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_FollowUp_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    overdue: null;
}): EmiStatus {
    return "pending" in value ? EmiStatus.pending : "paid" in value ? EmiStatus.paid : "overdue" in value ? EmiStatus.overdue : value;
}
function from_candid_variant_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _EmiInstallment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: EmiInstallment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_EmiInstallment_n74(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n66(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AppSettings;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AppSettings;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLog>): Array<ActivityLog> {
    return value.map((x)=>from_candid_ActivityLog_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n66(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmiInstallment>): Array<EmiInstallment> {
    return value.map((x)=>from_candid_EmiInstallment_n74(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUp>): Array<FollowUp> {
    return value.map((x)=>from_candid_FollowUp_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reminder>): Array<Reminder> {
    return value.map((x)=>from_candid_Reminder_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Array<Student> {
    return value.map((x)=>from_candid_Student_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n46(_uploadFile, _downloadFile, x));
}
function to_candid_LeadStatus_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentType_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_ReminderTargetType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReminderTargetType): _ReminderTargetType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n102(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    accountant: null;
} | {
    teamHead: null;
} | {
    admin: null;
} | {
    counselor: null;
} {
    return value == Role.accountant ? {
        accountant: null
    } : value == Role.teamHead ? {
        teamHead: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.counselor ? {
        counselor: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    bankTransfer: null;
} | {
    online: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.bankTransfer ? {
        bankTransfer: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReminderTargetType): {
    emi: null;
} | {
    followUp: null;
} | {
    payment: null;
} {
    return value == ReminderTargetType.emi ? {
        emi: null
    } : value == ReminderTargetType.followUp ? {
        followUp: null
    } : value == ReminderTargetType.payment ? {
        payment: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): {
    emi: null;
} | {
    full: null;
} {
    return value == PaymentType.emi ? {
        emi: null
    } : value == PaymentType.full ? {
        full: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    dropped: null;
} | {
    followUp: null;
} | {
    converted: null;
} {
    return value == LeadStatus.new ? {
        new_: null
    } : value == LeadStatus.dropped ? {
        dropped: null
    } : value == LeadStatus.followUp ? {
        followUp: null
    } : value == LeadStatus.converted ? {
        converted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
